name: DL_A3_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
 
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - tqdm
  - nltk
  - gensim
  - pytorch
  - torchvision
  - torchaudio
  - cpuonly
  - tensorboard
  - jupyterlab
  - notebook
  - ipykernel
  - jupytext
  - python-docx
  - pip
  - pip:
      - pretty-midi


# Use:
# cd Assignment3
# conda env create -f conda_requirement.yaml
# conda activate DL_A3_env


# Jupytext
# jupytext --sync assignment3.ipynb